// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQld1_zdc1g0kcXIg_hWS1nlgb07T8zR8',
    appId: '1:750817554168:web:3574910c7f081e9eab950d',
    messagingSenderId: '750817554168',
    projectId: 'imparfm',
    authDomain: 'imparfm.firebaseapp.com',
    databaseURL: 'https://imparfm-default-rtdb.firebaseio.com',
    storageBucket: 'imparfm.appspot.com',
    measurementId: 'G-T0XXG9NDG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASM7Gxd-bvEk3pD1hXEXusD67H-A2Trbk',
    appId: '1:750817554168:android:0a0092768e16eb3dab950d',
    messagingSenderId: '750817554168',
    projectId: 'imparfm',
    databaseURL: 'https://imparfm-default-rtdb.firebaseio.com',
    storageBucket: 'imparfm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJbtrk2O-8uyOFKyXwemXNNBbm1WAayA4',
    appId: '1:750817554168:ios:88ed7b137b245a90ab950d',
    messagingSenderId: '750817554168',
    projectId: 'imparfm',
    databaseURL: 'https://imparfm-default-rtdb.firebaseio.com',
    storageBucket: 'imparfm.appspot.com',
    androidClientId: '750817554168-1m78oi79so429q2bq0q2ciau5i9gg6lc.apps.googleusercontent.com',
    iosClientId: '750817554168-vblorb4ab2pepmro30800g9j1c9cmbb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJbtrk2O-8uyOFKyXwemXNNBbm1WAayA4',
    appId: '1:750817554168:ios:fc072d7fcd84e27bab950d',
    messagingSenderId: '750817554168',
    projectId: 'imparfm',
    databaseURL: 'https://imparfm-default-rtdb.firebaseio.com',
    storageBucket: 'imparfm.appspot.com',
    androidClientId: '750817554168-1m78oi79so429q2bq0q2ciau5i9gg6lc.apps.googleusercontent.com',
    iosClientId: '750817554168-soiji0c4omiv8lke6pmn1mmg5hu67au3.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp.RunnerTests',
  );
}
